[package]
name = "rust-memory-leak"
version = "0.1.0"
authors = ["Dmytrii Nagirniak <dnagir@gmail.com>"]

[[bin]]
name = "api"
path = "src/api.rs"

[dependencies]
log = "0.4"
env_logger = "0.5"
actix-web = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
